# Find GPU

In [115]:
%tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
Found GPU at: /device:GPU:0


# Import

In [116]:
import re
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# 2. Data Understanding & 3. Preprocessing

In [117]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [118]:
# Reading zawgyi data
"""
with open ('/content/drive/MyDrive/Colab Notebooks/NLP/zawgyi.zawgyi','r') as File:
  for i in File:
    print(i)
"""

"\nwith open ('/content/drive/MyDrive/Colab Notebooks/NLP/zawgyi.zawgyi','r') as File:\n  for i in File:\n    print(i)\n"

In [119]:
# Reading unicode data
"""
with open ('/content/drive/MyDrive/Colab Notebooks/NLP/unicode','r') as File:
  for i in File:
    print(i)
"""

"\nwith open ('/content/drive/MyDrive/Colab Notebooks/NLP/unicode','r') as File:\n  for i in File:\n    print(i)\n"

In [120]:
# Reading unicode data
unicode_data = []
with open ('/content/drive/MyDrive/Colab Notebooks/NLP/unicode','r') as File:
  for i in File:
    i = re.sub(r' ', r'', i)
    i = re.sub(r'([^\s])', r'\1 ', i)
    #print(i)
    unicode_data.append(i)
File.close()

In [121]:
unicode_data

['ယ ခ ု လ တ ွ င ် ပ ျ ာ း ရ ည ် န ှ င ် ့ ပ ျ ာ း ဖ ယ ေ ာ င ် း မ ျ ာ း က ိ ု စ ု ဆ ေ ာ င ် း က ြ သ ည ် ဟ ု ခ န ် ့ မ ှ န ် း န ိ ု င ် သ ည ် \n',
 'အ ခ န ် း ခ ထ ဲ မ ှ ာ ထ ည ် ့ လ ိ ု က ် ပ ါ \n',
 'ဆ ရ ာ က ြ ီ း ဦ း စ ိ န ် ၏ မ ြ န ် မ ာ အ ထ က ် တ န ် း က ျ ေ ာ င ် း မ ှ ၉ တ န ် း အ ေ ာ င ် မ ြ င ် ခ ဲ ့ ပ ြ ီ း မ င ် း လ ှ မ ြ ိ ု ့ န ေ ာ ် မ ံ က ျ ေ ာ င ် း မ ှ အ လ ယ ် တ န ် း ဆ ရ ာ ဖ ြ စ ် အ ေ ာ င ် မ ြ င ် ခ ဲ ့ ၏ \n',
 'ရ ှ စ ် လ ေ း လ ု ံ း လ ှ ု ပ ် ရ ှ ာ း မ ှ ု တ ွ င ် တ က ် က ြ ွ စ ွ ာ ပ ါ ဝ င ် ခ ဲ ့ သ လ ိ ု ဗ မ ာ န ိ ု င ် င ံ လ ု ံ း ဆ ိ ု င ် ရ ာ က ျ ေ ာ င ် း သ ာ း သ မ ဂ ္ ဂ မ ျ ာ း အ ဖ ွ ဲ ့ ခ ျ ု ပ ် မ ှ ာ လ ည ် း တ က ် က ြ ွ စ ွ ာ ပ ါ ဝ င ် လ ှ ု ပ ် ရ ှ ာ း ခ ဲ ့ သ ည ် \n',
 'ဗ ြ ိ တ ိ သ ျ ှ တ ပ ် မ ျ ာ း သ ည ် ဂ ျ ပ န ် မ ျ ာ း ၏ င ါ း ဖ မ ် း အ ိ မ ် ၃ ၀ ၀ ၀ ၀ ၀ ခ န ် ့ တ ွ င ် အ လ ု ပ ် လ ု ပ ် က ိ ု င ် န ေ က ြ ရ သ ည ် \n',
 'ဗ မ ာ မ ှ ာ လ ူ မ ျ ာ း စ ု ဗ မ ာ မ ျ ိ ု း န ွ ယ ် စ ု ၏ ခ ေ ါ ် ရ ာ တ ွ င ် တ ရ ာ း ဝ င ် ခ ေ ါ ် သ ေ ာ အ သ ု ံ း ဖ ြ စ ် သ ည ် \n',
 '

In [122]:
# Reading zawgyi data
zawgyi_data = []
with open ('/content/drive/MyDrive/Colab Notebooks/NLP/zawgyi.zawgyi','r') as File:
  for i in File:
    i = re.sub(r' ', r'', i)
    i = re.sub(r'([^\s])', r'\1 ', i)
    #print(i)
    zawgyi_data.append(i)
File.close()

In [123]:
zawgyi_data

['ယ ခ ု လ တ ြ င ္ ပ ် ာ း ရ ည ္ ႏ ွ င ္ ့ ပ ် ာ း ဖ ေ ယ ာ င ္ း မ ် ာ း က ိ ု စ ု ေ ဆ ာ င ္ း ၾ က သ ည ္ ဟ ု ခ န ္ ႔ မ ွ န ္ း ႏ ိ ု င ္ သ ည ္ \n',
 'အ ခ န ္ း ခ ထ ဲ မ ွ ာ ထ ည ္ ့ လ ိ ု က ္ ပ ါ \n',
 'ဆ ရ ာ ႀ က ီ း ဦ း စ ိ န ္ ၏ ျ မ န ္ မ ာ အ ထ က ္ တ န ္ း ေ က ် ာ င ္ း မ ွ ၉ တ န ္ း ေ အ ာ င ္ ျ မ င ္ ခ ဲ ့ ၿ ပ ီ း မ င ္ း လ ွ ၿ မ ိ ဳ ႕ ေ န ာ ္ မ ံ ေ က ် ာ င ္ း မ ွ အ လ ယ ္ တ န ္ း ဆ ရ ာ ျ ဖ စ ္ ေ အ ာ င ္ ျ မ င ္ ခ ဲ ့ ၏ \n',
 'ရ ွ စ ္ ေ လ း လ ု ံ း လ ႈ ပ ္ ရ ွ ာ း မ ႈ တ ြ င ္ တ က ္ ႂ က ြ စ ြ ာ ပ ါ ဝ င ္ ခ ဲ ့ သ လ ိ ု ဗ မ ာ ႏ ိ ု င ္ င ံ လ ု ံ း ဆ ိ ု င ္ ရ ာ ေ က ် ာ င ္ း သ ာ း သ မ ဂ ၢ မ ် ာ း အ ဖ ြ ဲ ႕ ခ ် ဳ ပ ္ မ ွ ာ လ ည ္ း တ က ္ ႂ က ြ စ ြ ာ ပ ါ ဝ င ္ လ ႈ ပ ္ ရ ွ ာ း ခ ဲ ့ သ ည ္ \n',
 'ၿ ဗ ိ တ ိ သ ွ ် တ ပ ္ မ ် ာ း သ ည ္ ဂ ် ပ န ္ မ ် ာ း ၏ င ါ း ဖ မ ္ း အ ိ မ ္ ၃ ၀ ၀ ၀ ၀ ၀ ခ န ္ ႔ တ ြ င ္ အ လ ု ပ ္ လ ု ပ ္ က ိ ု င ္ ေ န ၾ က ရ သ ည ္ \n',
 'ဗ မ ာ မ ွ ာ လ ူ မ ် ာ း စ ု ဗ မ ာ မ ် ိ ဳ း ႏ ြ ယ ္ စ ု ၏ ေ ခ ၚ ရ ာ တ ြ င ္ တ ရ ာ း ဝ င ္ ေ ခ ၚ ေ သ ာ အ သ ု ံ း ျ ဖ စ ္ သ ည ္ \n',
 '၂ ၀ ရ ာ စ ု 

In [124]:
len(unicode_data)

11000

In [125]:
len(zawgyi_data)

11000

In [126]:
# Train data of unicode_data 70%  & Test data of unicode_data 30%
len(unicode_data) * 0.7
train_unicode_data = unicode_data[0:7700]
test_unicode_data = unicode_data[7700:]

# Train data of zawgyi_data 70%  & Test data of zawgyi_data 30%
len(zawgyi_data) * 0.7
train_zawgyi_data = zawgyi_data[0:7700]
test_zawgyi_data = zawgyi_data[7700:]

In [127]:
# Labeling unicode : 1 & zawgyi : 0
train = train_unicode_data + train_zawgyi_data
train_labels = [1]*len(train_unicode_data) + [0]*len(train_zawgyi_data)
test = test_unicode_data + test_zawgyi_data
test_labels = [1]*len(test_unicode_data) + [0]*len(test_zawgyi_data)

In [128]:
# testing
[1]*2

[1, 1]

In [129]:
#train_labels

In [130]:
#test_labels

In [131]:
# labeling randomly (frequency ne' count myar tar ayin label )
oov_tok = '<OOV>' # out of vocab
sample = ['I am Nu Nu Hlaing']
tokenizer = Tokenizer(oov_token = oov_tok)
tokenizer.fit_on_texts(sample) # data char 1ku chin si number tat
word_index = tokenizer.word_index
word_index

{'<OOV>': 1, 'nu': 2, 'i': 3, 'am': 4, 'hlaing': 5}

In [132]:
# change to sequences
sequences = tokenizer.texts_to_sequences(sample)
sequences

[[3, 4, 2, 2, 5]]

In [133]:
max_length = 4182
trunc_type = 'post'  #put needed '0's for max length , if exceed, delete
vocab_size = 500  # firstmost 500 char ko be' frequency count
padded = pad_sequences(sequences,maxlen=max_length, truncating=trunc_type,padding='post') # length standard thet mhat
padded

array([[3, 4, 2, ..., 0, 0, 0]], dtype=int32)

In [134]:
#
tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(train)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(train)
train_padded = pad_sequences(sequences,maxlen=max_length, truncating=trunc_type,padding='post')
train_padded

array([[30, 25,  6, ...,  0,  0,  0],
       [16, 25, 15, ...,  0,  0,  0],
       [35, 18,  5, ...,  0,  0,  0],
       ...,
       [74, 80, 10, ...,  0,  0,  0],
       [13, 54,  6, ...,  0,  0,  0],
       [11, 41,  6, ...,  0,  0,  0]], dtype=int32)

In [135]:
embedding_dim = 64
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(1000, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid') #output layer sigmoid fun: ko use htar loz 0～1 output htwt mhr
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [136]:
type(train_labels)

list

In [137]:
num_epochs = 10
history = model.fit(train_padded, np.array(train_labels), epochs=num_epochs,verbose = 2)

Epoch 1/10
482/482 - 26s - loss: 0.1306 - accuracy: 0.9464 - 26s/epoch - 53ms/step
Epoch 2/10
482/482 - 16s - loss: 0.0424 - accuracy: 0.9886 - 16s/epoch - 33ms/step
Epoch 3/10
482/482 - 15s - loss: 0.0154 - accuracy: 0.9935 - 15s/epoch - 31ms/step
Epoch 4/10
482/482 - 15s - loss: 0.0113 - accuracy: 0.9953 - 15s/epoch - 31ms/step
Epoch 5/10
482/482 - 15s - loss: 0.0083 - accuracy: 0.9961 - 15s/epoch - 31ms/step
Epoch 6/10
482/482 - 15s - loss: 0.0078 - accuracy: 0.9967 - 15s/epoch - 32ms/step
Epoch 7/10
482/482 - 15s - loss: 0.1383 - accuracy: 0.9898 - 15s/epoch - 32ms/step
Epoch 8/10
482/482 - 15s - loss: 0.0655 - accuracy: 0.9949 - 15s/epoch - 31ms/step
Epoch 9/10
482/482 - 15s - loss: 0.0092 - accuracy: 0.9958 - 15s/epoch - 31ms/step
Epoch 10/10
482/482 - 15s - loss: 0.0094 - accuracy: 0.9956 - 15s/epoch - 32ms/step


In [138]:
model.save('/Unicode_Model.h5')

# 5. Evaluation

In [139]:
testing_sequences = tokenizer.texts_to_sequences(test)
testing_padded = pad_sequences(testing_sequences,maxlen=max_length, truncating=trunc_type,padding='post')
testing_padded

array([[11, 12,  7, ...,  0,  0,  0],
       [15, 10, 33, ...,  0,  0,  0],
       [12, 10,  5, ...,  0,  0,  0],
       ...,
       [89, 17,  5, ...,  0,  0,  0],
       [33,  7,  6, ...,  0,  0,  0],
       [33,  7,  6, ...,  0,  0,  0]], dtype=int32)

In [140]:
predicted_results = model.predict(testing_padded)
predicted_results

207/207 [==============================] - 1s 4ms/step


array([[1.11028254e-01],
       [1.00000000e+00],
       [1.00000000e+00],
       ...,
       [2.24371610e-20],
       [7.30588946e-17],
       [4.41245502e-17]], dtype=float32)

In [141]:
result = []
for i in predicted_results:
    if(i<0.5):
        result.append(0)
    else:
        result.append(1)

In [142]:
#result

In [143]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_labels, result)
print('confusion_matrix')
print(confusion_matrix)

confusion_matrix
[[3293    7]
 [  24 3276]]


In [144]:
# Evaluation Metrics
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score

print('Accuracy Score',accuracy_score(test_labels, result)*100,'%')
print('Precision Macro Score',precision_score(test_labels, result, average = 'macro')*100,'%')
print('Recall_Score',recall_score(test_labels, result, average = 'macro')*100,'%')
print('F1_Score',f1_score(test_labels, result, average = 'macro')*100,'%')

Accuracy Score 99.53030303030303 %
Precision Macro Score 99.53161750573545 %
Recall_Score 99.53030303030303 %
F1_Score 99.5302999140651 %


In [148]:
inputs = ['သီဟိုဠ်မှ ဉာဏ်ကြီးရှင်သည် အာယုဝဍ္ဎနဆေးညွှန်းစာကို ဇလွန်ဈေးဘေး ဗာဒံပင်ထက် အဓိဋ္ဌာန်လျက် ဂဃနဏဖတ်ခဲ့သည်။']
inputs = [re.sub(r' ', r'', i.strip()) for i in inputs]
inputs = [re.sub(r"([^\s])", r"\1 ", i.strip()) for i in inputs]
print(inputs)


testing_sequences = tokenizer.texts_to_sequences(inputs)
testing_padded = pad_sequences(testing_sequences,maxlen=4182, truncating=trunc_type,padding='post')

['သ ီ ဟ ိ ု ဠ ် မ ှ ဉ ာ ဏ ် က ြ ီ း ရ ှ င ် သ ည ် အ ာ ယ ု ဝ ဍ ္ ဎ န ဆ ေ း ည ွ ှ န ် း စ ာ က ိ ု ဇ လ ွ န ် ဈ ေ း ဘ ေ း ဗ ာ ဒ ံ ပ င ် ထ က ် အ ဓ ိ ဋ ္ ဌ ာ န ် လ ျ က ် ဂ ဃ န ဏ ဖ တ ် ခ ဲ ့ သ ည ် ။ ']


In [149]:
testing_padded

array([[12, 27, 41, ...,  0,  0,  0]], dtype=int32)

In [150]:
model.predict(testing_padded)

1/1 [==============================] - 0s 31ms/step


array([[1.]], dtype=float32)

In [151]:
inputs = ['သီဟိုဠ္မွ ဉာဏ္ႀကီးရွင္သည္ အာယုဝၯနေဆးၫႊန္းစာကို ဇလြန္ေဈးေဘး ဗာဒံပင္ထက္ အဓိ႒ာန္လ်က္ ဂဃနဏဖတ္ခဲ့သည္။']
inputs = [re.sub(r' ', r'', i.strip()) for i in inputs]
inputs = [re.sub(r"([^\s])", r"\1 ", i.strip()) for i in inputs]
print(inputs)


testing_sequences = tokenizer.texts_to_sequences(inputs)
testing_padded = pad_sequences(testing_sequences,maxlen=4182, truncating=trunc_type,padding='post')

['သ ီ ဟ ိ ု ဠ ္ မ ွ ဉ ာ ဏ ္ ႀ က ီ း ရ ွ င ္ သ ည ္ အ ာ ယ ု ဝ ၯ န ေ ဆ း ၫ ႊ န ္ း စ ာ က ိ ု ဇ လ ြ န ္ ေ ဈ း ေ ဘ း ဗ ာ ဒ ံ ပ င ္ ထ က ္ အ ဓ ိ ႒ ာ န ္ လ ် က ္ ဂ ဃ န ဏ ဖ တ ္ ခ ဲ ့ သ ည ္ ။ ']


In [152]:
model.predict(testing_padded)

1/1 [==============================] - 0s 80ms/step


array([[6.934236e-21]], dtype=float32)